In [1]:
actual = [1,0,1,1,0,1]
pred =  [1,1,1,0,0,0]

TP = FP = TN = FN = 0

for a,p in zip(actual, pred):
    if a==1 and p==1: TP += 1
    elif a==0 and p==1: FP += 1
    elif a==0 and p==0: TN += 1
    else: FN += 1

precision = TP/(TP+FP)
recall = TP/(TP+FN)
f1 = 2*precision*recall/(precision+recall)
accuracy = (TP+TN)/len(actual)

print(TP, FP, TN, FN)
print(accuracy, precision, recall, f1)

2 1 1 2
0.5 0.6666666666666666 0.5 0.5714285714285715


In [3]:
import numpy as np

m = np.array([[3,4,6],
              [2,9,7],
              [1,5,3]])

print("Rank:", np.linalg.matrix_rank(m))
print("Determinant:", np.linalg.det(m))
print("Inverse:\n", np.linalg.inv(m))

Rank: 3
Determinant: -14.000000000000004
Inverse:
 [[ 0.57142857 -1.28571429  1.85714286]
 [-0.07142857 -0.21428571  0.64285714]
 [-0.07142857  0.78571429 -1.35714286]]


In [25]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['NY', 'LA', 'Chicago']
}
df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago


In [5]:
import pandas as pd
import numpy as np

# Sample NumPy array
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Convert to DataFrame with column names
df = pd.DataFrame(data, columns=['A', 'B', 'C'])

print(df)


   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [9]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)  
y = pd.Series(data.target)                               
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.956140350877193
Precision: 0.9459459459459459
Recall: 0.9859154929577465
F1-score: 0.9655172413793104

Confusion Matrix:
 [[39  4]
 [ 1 70]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [ ]:
pip install -U scikit-learn
pip install pandas
pip install numpy

In [23]:
##Sentiment Analysis (Yes/No)
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
data = {
    'text': [
        "I love this product",
        "This is the worst experience",
        "Absolutely fantastic",
        "Not good at all",
        "I am very happy",
        "I hate this"
    ],
    'sentiment': [1, 0, 1, 0, 1, 0]  # 1 = Yes/Positive, 0 = No/Negative
}

df = pd.DataFrame(data)
X = df['text']
y = df['sentiment']
vectorizer = CountVectorizer()
X_vec = vectorizer.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_vec, y, test_size=0.33, random_state=42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.5

Classification Report:
               precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2



C:\Users\paidi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\paidi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\paidi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [21]:
##Disease Prediction (Yes/No)
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
data = load_breast_cancer()
X = data.data      
y = data.target    
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.956140350877193

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [27]:
#Classification  
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
#Sample dataset (Yes/No as 1/0)
data = {
    'feature1': [5, 2, 3, 8, 1, 6, 7, 4],
    'feature2': [1, 3, 5, 2, 8, 7, 4, 6],
    'target':    [1, 0, 0, 1, 0, 1, 1, 0]  # 1 = Yes, 0 = No
}
df = pd.DataFrame(data)
#Split features and target
X = df[['feature1', 'feature2']]
y = df['target']
#Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)
#Create and train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)
#Make predictions
y_pred = model.predict(X_test)
#Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
#Classification report with zero_division to avoid warnings
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division=0))

Accuracy: 0.5

Confusion Matrix:
 [[1 0]
 [1 0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

